### ISSUE TITLE
fuse.ico is missing

### ISSUE THREAD

**Issue by ghost** [Earu/Fuse#1]
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		File 'fuse.ico' cannot be found.	Fuse			
```

**Comment by Earu** [comment]
Yeah this is to be expected when building the whole thing yourself, you need to change the icon application project's properties![properties](https://puu.sh/A2VrR/3a37a5ed83.png)

**Comment by ghost** [comment]
fixed
